# Generated by Django 4.1.1 on 2022-09-27 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(default='', max_length=600, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Стоимость')),
                ('image', models.CharField(default='no image', max_length=200, verbose_name='Картинка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='market.category', verbose_name='Категория')),
            ],
        ),
    ]
